# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5c446afa7c01010028b2bd250bdb74903c97415a7fb1cc90037874beeca9046039532b2056e35efead61add2bde5050dc0c143b1398b944a5515937252dd768

test:
  secret_key_base: dff0202f5b83e44ca1ef963c1b366a1877167f279d5aa7eabcf8e8c8f66450e3add9270cc612c4ff6e2e0dfb1766cf3e13cc06441e624ceb7ca3fc5074c77e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
